FROM docker.io/library/ubuntu@sha256:2edbbc5dc405e9612ba3584ce95480277e3eb374407b5505fe26f17df77c7dbc
ENV DEBIAN_FRONTEND=noninteractive CMAKE_BUILD_PARALLEL_LEVEL=2
RUN sed -i '/^deb /{p;s/^deb /deb-src /;}' /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates python3 python3-pip cmake make pkg-config binutils-mingw-w64-x86-64 \
      gcc-mingw-w64-x86-64-win32 g++-mingw-w64-x86-64-win32 libz-mingw-w64-dev && \
    python3 -m pip install --no-cache-dir pyinstaller==6.16.0 && \
    mkdir /work && chmod 1777 /work
